### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Vysybyl** [thomasloupe/Slackord1#1]
Hi Thomas,

Thanks for the script, I used it to build what I needed (migrate several channels from Slack to Discord).

I haven't checked the latest commit, but the v0.5 can be greatly simplified:

1. You do not need to check "if key in dict.keys()". The standard pythonic way is "if key in dict"
2. The two functions can be refactored. You can have a single piece of code that returns you the messages:

```
def get_messages(folder, channel):
    for filename in sorted(glob(os.path.join(folder, channel, '*.json'))):
        with open(filename) as f:
            for message in json.load(f):
                mess = message['text']
                # here I have some logic to get the user name
                while len(mess) > 0:  # Discord does not like long messages
                    text = mess[:1800]
                    mess = mess[1800:]
                    # I'm using markdown bold and italic formatting
                    yield '**{user}** *({time})*: {text}'.format(
                        user=user,
                        time=datetime.fromtimestamp(float(message['ts'])).strftime('%Y-%m-%d %H:%M:%S'),
                        text=text
                    )
```

3. You do not need to install Slackord with pip. Considering it's a single file, it just need to be somewhere on the path.
4. I guess it should work fine from python 3.x (3.5 maybe?) you don't need to install python 3.7 specifically

Sorry for posting as an issue and not a PR. My code is not clean enough for that.

Take care,

**Comment by Vysybyl** [comment]
`def get_messages(folder, channel):
    for filename in sorted(glob(os.path.join(folder, channel, '*.json'))):
        with open(filename) as f:
            for message in json.load(f):
                mess = message['text']
                # here I have some logic to get the user name
                while len(mess) > 0:  # Discord does not like long messages
                    text = mess[:1800]
                    mess = mess[1800:]
                    # I'm using markdown bold and italic formatting
                    yield '**{user}** *({time})*: {text}'.format(
                        user=user,
                        time=datetime.fromtimestamp(float(message['ts'])).strftime('%Y-%m-%d %H:%M:%S'),
                        text=text
                    )`

**Comment by thomasloupe** [comment]
Hey @Vysybyl, thanks for your interest and for using Slackord! I realize there's a few issues with the 0.5 release that could certainly use improvements. Because of how inconvenient it was to get Slackord running for many people, I decided to redesign it using Tcl/Tkinter GUI. It's not quite finished yet, but I have released a pre-release alpha you can check out. Queues need to be set up at some point when I can find the time to do so, but this will allow file important, output window and more. At the moment it isn't functional but you're welcomed to have a go at it.

[Slackord pre-release 1.0a](https://github.com/thomasloupe/Slackord/releases/tag/1.0a)

**Comment by thomasloupe** [comment]
I've taken some of your advice on fixing some of the issues. I've completely reworked Slackord as a GUI app in Tkinter for Windows. Feel free to give it a shot and let me know if you come across any issues. Thanks!
[Slackord 1.0](https://github.com/thomasloupe/Slackord/releases/tag/1.0)
