### ISSUE TITLE
This looks great - does it work on backups?

### ISSUE THREAD

**Issue by cryptowally** [thomasloupe/Slackord1#2]
Since Slack Free plan only allows 10k message history to be visible, I set up daily backups to be taken of our Slack community long ago, before we hit the 10k limit.  So, it's been backing them up all this time, and now it's time to move to discord.

I'm wondering if this tool can work on these backups, and if it will do a good job and ignoring duplicates.  

Maybe I'll need to combine/deduplicate the messages first, make sure they're organized into a different file per channel, and then use the tool to upload, but I thought I'd ask if you had any suggestions.

**Comment by thomasloupe** [comment]
Hey there, @cryptowally.
Yes, Slackord should work just fine for any backups as long as they're in JSON format. There is a known bug with threading that will lock up the main thread but the history will still get parsed and the messages will still post. 

If you're unsure yet on whether you'd like to use it, I'd suggest setting up a test Discord server and giving it a shot. Perhaps I will release some GIFs of the bot in action as well later.
